### ISSUE TITLE
Multiple custom elements error

### ISSUE THREAD

**Issue by tomlut** [Yevgenium/weather-chart-card#95]
I've just started getting this error but have not changed the config of my cards for ages:
```
Logger: frontend.js.latest.202202031
Source: components/system_log/__init__.py:190 
First occurred: 23:28:57 (1 occurrences) 
Last logged: 23:28:57

http://10.1.1.100:8123/hacsfiles/weather-chart-card/weather-chart-card.js?hacstag=163941792120:15296:24 NotSupportedError: Cannot define multiple custom elements with the same tag name
``` 

Config:
```
type: custom:weather-chart-card
entity: weather.weatherflow_day_based_forecast
show_main: false
show_attributes: false
title: Daily Forecast
```

The card seems to be working fine.

**Comment by tomlut** [comment]
I just tries to specify this as well:
``` 
temperature1_color: rgba(255, 152, 0, 1.0)
``` 

it made no difference to the line colour.

**Comment by tomlut** [comment]
Yes. 

After updating to 2022.3 I am now getting:

```
Logger: frontend.js.latest.202203010
Source: components/system_log/__init__.py:190
First occurred: 08:08:04 (1 occurrences)
Last logged: 08:08:04

http://10.1.1.100:8123/frontend_latest/app.41ffbdd2.js:850:0 Error: Failed to execute 'define' on 'CustomElementRegistry': the name "weather-chart-card" has already been used with this registry
```

**Comment by tomlut** [comment]
That second error was caused by there being two resources defined. Not sure how that happened. Maybe when I tried to roll back to a previous version using HACS?

![Screenshot 2022-03-03 at 09-16-23 Configuration – Home Assistant](https://user-images.githubusercontent.com/10679300/156459189-57b81338-bbca-44e0-873a-5399ec97a09e.png)

Removing one of the entries seems to have resolved all the issues.
